from common.configuration import (
    MONGO_URI,
    PCM_COLLECTION_COMMENTS,
    PCM_COLLECTION_GROUPS,
    PCM_COLLECTION_PAGES,
    PCM_COLLECTION_POSTS,
    PCM_COLLECTION_PROJECTS,
    PCM_COLLECTION_USERS,
    PCM_DATABASE,
)
from pymongo import MongoClient, collection, database

DB_CLIENT: MongoClient = MongoClient(MONGO_URI, serverSelectionTimeoutMS=10000)

DB_DATABASE: database = DB_CLIENT[PCM_DATABASE]

DB_POSTS: collection = DB_DATABASE[PCM_COLLECTION_POSTS]
DB_PROJECTS: collection = DB_DATABASE[PCM_COLLECTION_PROJECTS]
DB_GROUPS: collection = DB_DATABASE[PCM_COLLECTION_GROUPS]
DB_USERS: collection = DB_DATABASE[PCM_COLLECTION_USERS]
DB_COMMENTS: collection = DB_DATABASE[PCM_COLLECTION_COMMENTS]
DB_PAGES: collection = DB_DATABASE[PCM_COLLECTION_PAGES]
